First possible working script!

diff --git a/equinix-floating-ip b/equinix-floating-ip
--- a/equinix-floating-ip
+++ b/equinix-floating-ip
@@ -41,6 +41,11 @@ OCF_RESKEY_ip_default=""
 : ${OCF_RESKEY_equinixfact=${OCF_RESKEY_equinixfact_default}}
 : ${OCF_RESKEY_ip=${OCF_RESKEY_ip_default}}
 
+# Load in Equinix machine UUID and token
+MACHINE_UUID=$(crudini --get OCF_RESKEY_ip '' equinix_uuid)
+EQUINIX_TOKEN=$(crudini --get OCF_RESKEY_ip '' equinix_token)
+# Set this yourself
+EQUINIX_PROJECT="5f3c29b7-bda3-4f3b-8957-19b1f4b4b6ec"
 #######################################################################
 
 
@@ -64,7 +69,8 @@ cat <<END
 <longdesc lang="en">
 Resource Agent to move a floating IP address from an instance to another one.
 It relies on an Ansible-style fact stored as /etc/ansible/facts.d/uuid.fact to retrieve
-a machine UUID and API token with which to move that token to that machine.
+a machine UUID and API token with which to move that token to that machine, as well as
+Crudini being installed to make it reasonably safe to parse the facts file.
 </longdesc>
 <shortdesc lang="en">Move a floating IP</shortdesc>
 
@@ -101,29 +107,14 @@ END
 }
 
 emflip_validate() {
-	check_binary "$OCF_RESKEY_openstackcli"
-
-	if [ -z "$OCF_RESKEY_openrc" ]; then
-		ocf_exit_reason "openrc parameter not set"
+	if [ -z "$MACHINE_UUID" ]; then
+		ocf_exit_reason "machine UUID not set"
 		return $OCF_ERR_CONFIGURED
 	fi
 
-	if [ ! -f "$OCF_RESKEY_openrc" ] ; then
-		ocf_exit_reason "openrc file not found"
+	if [ ! -f "$EQUINIX_TOKEN" ] ; then
+		ocf_exit_reason "equinix metal token not found"
 		return $OCF_ERR_CONFIGURED
-	fi
-
-	. $OCF_RESKEY_openrc
-
-	if ! $OCF_RESKEY_openstackcli floating ip list|grep -q $OCF_RESKEY_ip_id ; then
-		ocf_exit_reason "ip-id $OCF_RESKEY_ip_id not found"
-		return $OCF_ERR_CONFIGURED
-	fi
-
-	${HA_SBIN_DIR}/attrd_updater --query -n openstack_ports -N $(crm_node -n) > /dev/null 2>&1
-	if [ $? -ne 0 ] ; then
-		ocf_log warn "attr_updater failed to get openstack_ports attribute of node $OCF_RESOURCE_INSTANCE"
-		return $OCF_ERR_GENERIC
 	fi
 
 	return $OCF_SUCCESS
@@ -132,35 +123,28 @@ emflip_validate() {
 emflip_monitor() {
 	local result
 	local floating_ip
-	local node_port_ids
-	local port
-	local buffer
 	local crm_node
 
 	crm_node=$(crm_node -n)
-	node_port_ids=$(${HA_SBIN_DIR}/attrd_updater --query -n openstack_ports -N $crm_node \
-		| awk -F= '{gsub("\"","");print $NF}' \
-		| tr ',' ' ' \
-		| awk -F: '{print $NF}')
 
 	# Is the IP active and attached?
-	result=$($OCF_RESKEY_openstackcli floating ip show \
-		--column port_id --column floating_ip_address \
-		--format yaml \
-		$OCF_RESKEY_ip_id)
+	currently_assigned=$(curl -X GET \
+	-H "Content-Type: application/json" \
+	-H "X-Auth-Token: $EQUINIX_TOKEN" \
+	"https://api.equinix.com/metal/v1/projects/$EQUINIX_PROJECT/ips?types=private_ipv4&include=assignments.assigned_to" | jq -r '.ip_addresses[] | select(.network == "10.70.197.128")' | jq -r '.assignments[] | select(.address == "10.70.197.254")' | jq -r '.assigned_to.hostname')
 
-	for port in $node_port_ids ; do
-		if echo $result | grep -q $port ; then
-			floating_ip=$(echo $result | awk '/floating_ip_address/ {print $2}')
-			${HA_SBIN_DIR}/attrd_updater ${OCF_RESKEY_delay} -S status -n openstack_floating_ip -v $floating_ip
+	assignment_id=$(curl -X GET \
+	-H "Content-Type: application/json" \
+	-H "X-Auth-Token: $EQUINIX_TOKEN" \
+	"https://api.equinix.com/metal/v1/projects/$EQUINIX_PROJECT/ips?types=private_ipv4&include=assignments.assigned_to" | jq -r '.ip_addresses[] | select(.network == "10.70.197.128")' | jq -r '.assignments[] | select(.address == "10.70.197.254")' | jq -r '.id')
 
-			return $OCF_SUCCESS
-		fi
-	done
-
-	${HA_SBIN_DIR}/attrd_updater ${OCF_RESKEY_delay} -D -S state -n openstack_floating_ip
-	ocf_log warn "$OCF_RESKEY_ip_id is not attached to any fixed address"
-	return $OCF_NOT_RUNNING
+	if $currently_assigned == $crm_node ; then
+		ocf_log info "$OCF_RESKEY_IP is attached to this machine"
+		return $OCF_SUCCESS
+	else
+		ocf_log warn "$OCF_RESKEY_IP is not attached to this machine"
+		return $OCF_NOT_RUNNING
+	endif
 }
 
 emflip_stop() {
@@ -172,7 +156,10 @@ emflip_stop() {
 		return $OCF_SUCCESS
 	fi
 
-	if ! $OCF_RESKEY_openstackcli floating ip unset --port $OCF_RESKEY_ip_id ; then
+	if ! (curl -X DELETE \
+        -H "Content-Type: application/json" \
+        -H "X-Auth-Token: $EQUINIX_TOKEN" \
+        "https://api.equinix.com/metal/v1/ips/$assignment_id") ; then
 		return $OCF_ERR_GENERIC
 	fi
 
@@ -187,34 +174,42 @@ emflip_stop() {
 }
 
 emflip_start() {
-	local node_port_id
-	local node_port_ids
-
 	emflip_monitor
 	if [ $? = $OCF_SUCCESS ]; then
-		ocf_log info "$OCF_RESKEY_ip_id already started"
+		ocf_log info "$OCF_RESKEY_ip already started"
 		return $OCF_SUCCESS
 	fi
 
-	# Get port_id from subnet_id
-	node_port_ids=$(${HA_SBIN_DIR}/attrd_updater --query -n openstack_ports -N $(crm_node -n) \
-		| awk '{gsub("value=","") ; gsub("\"","") ; print $NF}')
+	ocf_log info "Moving IP address $OCF_RESKEY_ip to UUID $MACHINE_UUID"
 
-	node_port_id=$(echo $node_port_ids \
-		| tr ',' '\n' \
-		| awk -F: "/$OCF_RESKEY_subnet_id/ {print \$2}")
+	if ! (curl -X DELETE \
+        -H "Content-Type: application/json" \
+        -H "X-Auth-Token: $EQUINIX_TOKEN" \
+        "https://api.equinix.com/metal/v1/ips/$assignment_id") ; then
+		ocf_log warn "Failed to unset existing IP, this may be fine"
+	fi
 
-	ocf_log info "Moving IP address $OCF_RESKEY_ip_id to port ID $node_port_id"
+	curl -X POST \
+	-H "Content-Type: application/json" \
+	-H "X-Auth-Token: $EQUINIX_TOKEN" \
+	"https://api.equinix.com/metal/v1/devices/$MACHINE_UUID/ips" \
+	-d '{
+        "address": "10.70.197.254/32"
+	}'
 
-	$OCF_RESKEY_openstackcli floating ip set --port $node_port_id $OCF_RESKEY_ip_id
+	if [ $? == 0 ]; then
+		ocf_log info "$OCF_RESKEY_ip successfully assigned!"
+		return $OCF_SUCCESS
+	fi
+
 	if [ $? != $OCF_SUCCESS ]; then
-		ocf_log error "$OCF_RESKEY_ip_id Cannot be set to port $node_port_id"
+		ocf_log error "$OCF_RESKEY_ip cannot be set to UUID $MACHINE_UUID, check your UUID and API token"
 		return $OCF_ERR_GENERIC
 	fi
 
 	emflip_monitor
 	if [ $? != $OCF_SUCCESS ]; then
-		ocf_log error "$OCF_RESKEY_ip_id Cannot be set to port $node_port_id"
+		ocf_log error "$OCF_RESKEY_ip was set for UUID $MACHINE_UUID but what we fetched says otherwise"
 		return $OCF_ERR_GENERIC
 	fi
 
